default: &default
  adapter: postgresql
  username: fahad
  password: 11223344
  pool: 15
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: instagram-app

test:
  <<: *default
  database: instagram-test-app

production:
  <<: *default
  database: instagram-production-app